const{MessageEmbed}=require("discord.js");
const{stripIndents}=require("common-tags");
const{version}=require("../../package.json");
const config=require("../../json/u/config.json");
const server=require("../../json/d/server.json");
const functions=require("../../functions.js");
module.exports={name:"help",aliases:["h"],category:"❓ ✦ info",description:"To view the help command",usage:"<prefix>help [command-name]",run:async(client,message,args)=>{if(args[0]){getCMD(client,message,args[0])}else{getAll(client,message)}}};
function getAll(client,message){const embed=new MessageEmbed().setColor(functions.color(message)).setTitle("**❓ HELP**").setTimestamp().setThumbnail(functions.icon(message));
const state=server[message.guild.id].server.categories;
if(server[message.guild.id].language==0)embed.setDescription("**This is the ` "+version+" ` version.**\n\n💡 Dm me ` register ` to register yourself.\n➕ You can as well, type ` "+server[message.guild.id].server.prefix+"help [command-name] ` to have details for a command.").addField("** **","** **");
else{embed.setDescription("**C'est la version ` "+version+" `.**\n\n💡 Mp moi ` register ` pour t'inscrire sur mon réseau.\n➕ Tu peux aussi écrire ` "+server[message.guild.id].server.prefix+"help [commande] ` pour avoir des détails sur une commande.").addField("** **","** **");}
const commands=(category)=>{return client.commands.filter(cmd=>cmd.category==category).map(cmd=>server[message.guild.id].server.prefix+cmd.name).join("\n")};
client.categories.map(cat=>{if(cat=="🎛️ ✦ config"){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="🌈 ✦ fun"&&state.fun==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="🎮 ✦ games"&&state.games==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,false)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="🔞 ✦ nsfw"&&state.nsfw==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="🚨 ✦ utilities"&&state.utilities==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="❓ ✦ info"&&state.info==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="🔍 ✦ search"&&state.search==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
client.categories.map(cat=>{if(cat=="🔨 ✦ moderation"&&state.moderation==true){embed.addField(stripIndents`${cat.toUpperCase()}`,`**\`\`\`fix\n${commands(cat)}\`\`\`**`,true)}}).reduce((string,category)=>string+"\n"+category);
return message.channel.send(embed.addField("** **","** **").addField("📋 ~ Credits :", "- 𝗗𝘂 𝗖𝗮𝘀𝘀𝗼𝘂𝗹𝗲𝘁#5011\n- 𝗗𝘂 𝗖𝗼𝘂𝘀𝗰𝗼𝘂𝘀#7622",true).addField("🎫 ~ Invite me", "[CLICK HERE](https://discord.com/api/oauth2/authorize?client_id=746402751621234769&permissions=1812327649&scope=bot)",true))};
function getCMD(client,message,input){const cmd=client.commands.get(input.toLowerCase())||client.commands.get(client.aliases.get(input.toLowerCase()));
let embed=new MessageEmbed().setColor(functions.color(message)).setFooter(`Syntax: <> = required, [] = optionnal`).setTitle("**❓ HELP**").setTimestamp().setThumbnail(functions.icon(message));
let info=`No information found for command **${input.toLowerCase()}**`;
if(!cmd){return message.channel.send(embed.setColor(config.Cerr).setDescription("**💢 Error**\n"+info).setThumbnail(config.Ierr))};
if(cmd.name)info=`**・Command name** :\n\`\`\`${cmd.name}\`\`\``;
if(cmd.category)info+=`**\n・Category** :\n\`\`\`${cmd.category}\`\`\``;
if(cmd.aliases)info+=`\n**・Aliases** :\n\`\`\`${cmd.aliases.map(a=>`${a}`).join(", ")}\`\`\``;
if(cmd.description)info+=`\n**・Description** :\n\`\`\`${cmd.description}\`\`\``;
if(cmd.usage)info+=`\n**・Usage** :\n\`\`\`${cmd.usage}\`\`\``;
return message.channel.send(embed.setDescription(info))};