const{MessageEmbed}=require("discord.js");
const config=require("../../json/u/config.json");
const user=require("../../json/d/user.json");
const server=require("../../json/d/server.json");
module.exports={
    name:"stats",category:"❓ ✦ info",
    description:"To view your friend stats",usage:"<prefix>stats [game] [mention]",
    run:async(client,message,args,tools)=>{
        if(tools.category(message,"info")){
            try{
                var embed=new MessageEmbed().setColor(tools.color(message)).setThumbnail(tools.icon(message)).setTimestamp().setTitle("**📜 STATS**");
                let msg;
                switch(args[0]){
                    case"power4":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats)*10000)/100+"%",true));
                    break;
                    case"find-me":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.findme.defeats)*10000)/100+"%",true));
                    break;
                    case"flip-coin":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.flipcoin.defeats)*10000)/100+"%",true));
                    break;
                    case"memory":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats)*10000)/100+"%",true));
                    break;
                    case"pacman":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games[args[0]].defeats)*10000)/100+"%",true));
                    break;
                    case"rock-paper-scissors":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.rps.defeats)*10000)/100+"%",true));
                    break;
                    case"slot-machine":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.slotmachine.defeats)*10000)/100+"%",true));
                    break;
                    case"tic-tac-toe":
                    msg=await message.channel.send(embed.addField("Games played",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.defeats,true).addField("Victories",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.wins,true).addField("Defeats",server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.defeats,true).addField("Ratio",Math.round((server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.wins/server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.defeats)*100)/100,true).addField("Win rate",Math.round(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.wins/(server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.wins+server[message.guild.id].users[tools.user(message,args[1]).user.id].games.tictactoe.defeats)*10000)/100+"%",true));
                    break;
                };
            }catch(e){
                if(tools.language(message)==0){
                    message.channel.send(new MessageEmbed().setColor(config.Cerr).setThumbnail(config.Ierr).setTimestamp().setDescription("**💢 Error\nThis user doesn't have any stats.**"));
                }else{
                    message.channel.send(new MessageEmbed().setColor(config.Cerr).setThumbnail(config.Ierr).setTimestamp().setDescription("**💢 Erreur\nCette personne n'a pas de stats.**"));
                };
                return;
            };
            if(tools.user(message,args[0],false)){
                msg=await message.channel.send(embed.addField("Games played",tools.rUser(message,tools.user(message,args[0],false).user.id)+tools.rUser(message,tools.user(message,args[0],false).user.id,1),true).addField("Wins",tools.rUser(message,tools.user(message,args[0],false).user.id),true).addField("Defeats",tools.rUser(message,tools.user(message,args[0],false).user.id,1),true).addField("Ratio",Math.round((tools.rUser(message,tools.user(message,args[0],false).user.id)/tools.rUser(message,tools.user(message,args[0],false).user.id,1))*100)/100,true).addField("Win rate",Math.round(tools.rUser(message,tools.user(message,args[0],false).user.id)/(tools.rUser(message,tools.user(message,args[0],false).user.id)+tools.rUser(message,tools.user(message,args[0],false).user.id,1))*10000)/100+"%",true));
            }else if(args[0]!="power4"&&args[0]!="find-me"&&args[0]!="flip-coin"&&args[0]!="memory"&&args[0]!="pacman"&&args[0]!="rock-paper-scissors"&&args[0]!="slot-machine"&&args[0]!="tic-tac-toe"){
                if(tools.language(message)==0){
                    message.channel.send(new MessageEmbed().setColor(config.Cerr).setThumbnail(config.Ierr).setTimestamp().setDescription("**💢 Error\nYou must write correct arguments**\nTry that :\n```"+tools.prefix(message)+module.exports.name+"```"))
                }else{
                    message.channel.send(new MessageEmbed().setColor(config.Cerr).setThumbnail(config.Ierr).setTimestamp().setDescription("**💢 Erreur\nVous devez écrire des arguments corrects**\nEssaye ça :\n```"+tools.prefix(message)+module.exports.name+"```"))
                };
            };
            msg.react("👤").then(r=>{
                const filter=(reaction,user)=>reaction.emoji.name=="👤"&&user.id==message.author.id;
                const reaction=msg.createReactionCollector(filter,{time:60000});
                reaction.on("collect",r=>{
                    switch(args[0]){
                        case"power4":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games[args[0]].wins+user[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games[args[0]].wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games[args[0]].wins/user[tools.user(message,args[1]).user.id].games[args[0]].defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games[args[0]].wins/(user[tools.user(message,args[1]).user.id].games[args[0]].wins+user[tools.user(message,args[1]).user.id].games[args[0]].defeats)*10000)/100+"%",true));
                        break;
                        case"find-me":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games.findme.wins+user[tools.user(message,args[1]).user.id].games.findme.defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games.findme.wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games.findme.defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games.findme.wins/user[tools.user(message,args[1]).user.id].games.findme.defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games.findme.wins/(user[tools.user(message,args[1]).user.id].games.findme.wins+user[tools.user(message,args[1]).user.id].games.findme.defeats)*10000)/100+"%",true));
                        break;
                        case"flip-coin":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games.flipcoin.wins+user[tools.user(message,args[1]).user.id].games.flipcoin.defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games.flipcoin.wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games.flipcoin.defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games.flipcoin.wins/user[tools.user(message,args[1]).user.id].games.flipcoin.defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games.flipcoin.wins/(user[tools.user(message,args[1]).user.id].games.flipcoin.wins+user[tools.user(message,args[1]).user.id].games.flipcoin.defeats)*10000)/100+"%",true));
                        break;
                        case"memory":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games[args[0]].wins+user[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games[args[0]].wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games[args[0]].wins/user[tools.user(message,args[1]).user.id].games[args[0]].defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games[args[0]].wins/(user[tools.user(message,args[1]).user.id].games[args[0]].wins+user[tools.user(message,args[1]).user.id].games[args[0]].defeats)*10000)/100+"%",true));
                        break;
                        case"pacman":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games[args[0]].wins+user[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games[args[0]].wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games[args[0]].defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games[args[0]].wins/user[tools.user(message,args[1]).user.id].games[args[0]].defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games[args[0]].wins/(user[tools.user(message,args[1]).user.id].games[args[0]].wins+user[tools.user(message,args[1]).user.id].games[args[0]].defeats)*10000)/100+"%",true));
                        break;
                        case"rock-paper-scissors":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games.rps.wins+user[tools.user(message,args[1]).user.id].games.rps.defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games.rps.wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games.rps.defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games.rps.wins/user[tools.user(message,args[1]).user.id].games.rps.defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games.rps.wins/(user[tools.user(message,args[1]).user.id].games.rps.wins+user[tools.user(message,args[1]).user.id].games.rps.defeats)*10000)/100+"%",true));
                        break;
                        case"slot-machine":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games.slotmachine.wins+user[tools.user(message,args[1]).user.id].games.slotmachine.defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games.slotmachine.wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games.slotmachine.defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games.slotmachine.wins/user[tools.user(message,args[1]).user.id].games.slotmachine.defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games.slotmachine.wins/(user[tools.user(message,args[1]).user.id].games.slotmachine.wins+user[tools.user(message,args[1]).user.id].games.slotmachine.defeats)*10000)/100+"%",true));
                        break;
                        case"tic-tac-toe":
                        message.channel.send(embed.addField("Games played",user[tools.user(message,args[1]).user.id].games.tictactoe.wins+user[tools.user(message,args[1]).user.id].games.tictactoe.defeats,true).addField("Victories",user[tools.user(message,args[1]).user.id].games.tictactoe.wins,true).addField("Defeats",user[tools.user(message,args[1]).user.id].games.tictactoe.defeats,true).addField("Ratio",Math.round((user[tools.user(message,args[1]).user.id].games.tictactoe.wins/user[tools.user(message,args[1]).user.id].games.tictactoe.defeats)*100)/100,true).addField("Win rate",Math.round(user[tools.user(message,args[1]).user.id].games.tictactoe.wins/(user[tools.user(message,args[1]).user.id].games.tictactoe.wins+user[tools.user(message,args[1]).user.id].games.tictactoe.defeats)*10000)/100+"%",true));
                        break;
                    };
                    if(tools.user(message,args[0],false)){
                        message.channel.send(embed.addField("Games played",tools.rServer(message,tools.user(message,args[0],false).user.id)+tools.rServer(message,tools.user(message,args[0],false).user.id,1),true).addField("Wins",tools.rServer(message,tools.user(message,args[0],false).user.id),true).addField("Defeats",tools.rServer(message,tools.user(message,args[0],false).user.id,1),true).addField("Ratio",Math.round((tools.rServer(message,tools.user(message,args[0],false).user.id)/tools.rServer(message,tools.user(message,args[0],false).user.id,1))*100)/100,true).addField("Win rate",Math.round(tools.rServer(message,tools.user(message,args[0],false).user.id)/(tools.rServer(message,tools.user(message,args[0],false).user.id)+tools.rServer(message,tools.user(message,args[0],false).user.id,1))*10000)/100+"%",true));
                    };
                    msg.edit(embed);
                    msg.reactions.removeAll();
                });
            });
        }else{
            if(tools.language(message)==0){
                message.channel.send(new MessageEmbed().setColor(config.Cerr).setThumbnail(config.Ierr).setTimestamp().setDescription("**💢 Error\nThe category \"info\" isn't enabled.**\nTry this :\n```"+tools.prefix(message)+"category info enable```"));
            }else{
                message.channel.send(new MessageEmbed().setColor(config.Cerr).setThumbnail(config.Ierr).setTimestamp().setDescription("**💢 Erreur\nLa catégorie \"info\" n'est pas activée.**\nEssaye ça :\n```"+tools.prefix(message)+"category info enable```"));
            };
        };
    }
};